# Thông tin tổng quan của file

In [7]:
import pandas as pd

# Đọc file CSV vào DataFrame
file_path = r'D:\UNIDOCS\OLAP\IS217.R11-OLAP\PythonScripts\cleaned-data\cleaned-majors.csv'
df = pd.read_csv(file_path, encoding='utf-8')
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   major_group_id     506 non-null    int64
 1   major_group_name   506 non-null    str
 2   major_id           506 non-null    int64
 3   major_name         506 non-null    str
 4   major_description  484 non-null    str
 5   score_codes        506 non-null    str
dtypes: int64(2), str(4)
memory usage: 23.8 KB

,major_group_id,major_group_name,major_id,major_name,major_description,score_codes
0,1,Kế toán - Kiểm toán,910,Quản trị tài chính kế toán,Quản trị tài chính kế toán,D404;7340101_02
1,1,Kế toán - Kiểm toán,1,Kế toán,Tài chính và Kế toán (BFA); Kế toán; Kế toán d...,7340301;7340301DKD;7340301DKK;7340301DL;734030...
2,1,Kế toán - Kiểm toán,2,Kiểm toán,Kế toán kiểm toán (ngành Kế toán); Kiểm toán (...,7340302;7340302DKD;7340302DKK;7340302_409;ACT0...
3,2,Tài chính - Ngân hàng - Bảo hiểm,904,Kinh tế và quản lý bất động sản,Kinh tế và quản lý bất động sản,GTADCKB2
4,2,Tài chính - Ngân hàng - Bảo hiểm,3,Tài chính,Tài chính doanh nghiệp (theo định hướng ACCA);...,TM24;TM25;TM26;TM27;7340201QT01.11;EP10;734020...

# Kiểm tra giá trị rỗng

In [8]:
df.isna().sum()

major_group_id        0
major_group_name      0
major_id              0
major_name            0
major_description    22
score_codes           0
dtype: int64

**Kết luận**: Các cột bị thiếu dữ liệu đều thuộc về major_description là cột không quan trọng, nên không cần bổ sung / lược bỏ các hàng này.

## Chuẩn hóa danh sách và chuỗi

In [9]:
import re

def remove_newlines(val):
    if pd.isna(val):
        return val
    if isinstance(val, str):
        return re.sub(r'[\r\n]+', ' ', val).strip()
    return val

df = df.map(remove_newlines)

def normalize_score_codes(val):
    if pd.isna(val) or str(val).strip() == '':
        return val
    s = str(val).replace(',', ';')
    s = re.sub(r'\s+', '', s)
    return s

df['score_codes'] = df['score_codes'].apply(normalize_score_codes)

# Lưu

In [10]:
output_path = r'D:\UNIDOCS\OLAP\IS217.R11-OLAP\PythonScripts\cleaned-data\cleaned-majors.csv'
df.to_csv(output_path, index=False)
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   major_group_id     506 non-null    int64
 1   major_group_name   506 non-null    str
 2   major_id           506 non-null    int64
 3   major_name         506 non-null    str
 4   major_description  484 non-null    str
 5   score_codes        506 non-null    str
dtypes: int64(2), str(4)
memory usage: 23.8 KB

,major_group_id,major_group_name,major_id,major_name,major_description,score_codes
0,1,Kế toán - Kiểm toán,910,Quản trị tài chính kế toán,Quản trị tài chính kế toán,D404;7340101_02
1,1,Kế toán - Kiểm toán,1,Kế toán,Tài chính và Kế toán (BFA); Kế toán; Kế toán d...,7340301;7340301DKD;7340301DKK;7340301DL;734030...
2,1,Kế toán - Kiểm toán,2,Kiểm toán,Kế toán kiểm toán (ngành Kế toán); Kiểm toán (...,7340302;7340302DKD;7340302DKK;7340302_409;ACT0...
3,2,Tài chính - Ngân hàng - Bảo hiểm,904,Kinh tế và quản lý bất động sản,Kinh tế và quản lý bất động sản,GTADCKB2
4,2,Tài chính - Ngân hàng - Bảo hiểm,3,Tài chính,Tài chính doanh nghiệp (theo định hướng ACCA);...,TM24;TM25;TM26;TM27;7340201QT01.11;EP10;734020...